server:
  port: 8006

#服务别名----注册zookeeper到注册中心名称
spring:
  application:
    name: cloud-payment-consul-service
  # zookeeper服务地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}